version: '3.9'

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local

services:
  prometheus-2:
    image: prom/prometheus:latest
    container_name: prometheus-2
    ports:
      - "9090:9090"
    volumes:
      - /etc/prometheus:/config
      - prometheus-data:/prometheus
    restart: unless-stopped
    network_mode: host
    command:
      - "--config.file=/config/prometheus.yaml"


  grafana:
    image: grafana/grafana:latest
    container_name: grafana-2
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    network_mode: host
    restart: unless-stopped
    depends_on:
      - prometheus-2